<?php

namespace LibraryBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findBook($title)
//    {
//        $req=$this->getEntityManager();
//        return  $req->createQuery("SELECT b FROM LibraryBundle:Book b WHERE b.booktitle LIKE :s ")
//            ->setParameter('s',$title.'%')
//            ->getResult();
//    }

    public function findBook($title){
        $query=$this->getEntityManager()->createQuery( "select a from LibraryBundle:Book a where a.booktitle='$title'");
        return $query->getResult();
    }
}
