<?php

namespace LibraryBundle\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    public function issue($id)
    {
        $q = $this->getEntityManager()->createQuery("UPDATE LibraryBundle:Book b SET b.bookquantity= b.bookquantity-1 WHERE b.bookid='$id'");
        return $q->getResult();
    }

    public function incrementStock($booktitle)
    {

        $req=$this->getEntityManager();
        return  $req->createQuery("UPDATE LibraryBundle:Book b SET b.bookquantity= b.bookquantity+1 WHERE b.booktitle like :s ")
            ->setParameter('s',$booktitle.'%')
            ->getResult();
    }



    public function updateAvail($id)
    {
        $q = $this->getEntityManager()->createQuery("UPDATE LibraryBundle:Book b SET b.bookavail='0' WHERE b.bookid='$id'");
        return $q->getResult();
    }
    public function updateAvailTrue($booktitle)
    {
        $req=$this->getEntityManager();
        return $req->createQuery("UPDATE LibraryBundle:Book b SET b.bookavail='1' WHERE b.booktitle like :s")
            ->setParameter('s',$booktitle.'%')
            ->getResult();
    }
}
