<?php
namespace PlanEventBundle\Repository;
/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFeed($id){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Avis c  where c.iduser='$id'");
        return $query->getResult();
    }


}