<?php
namespace PlanEventBundle\Repository;
/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateNbrPlaceEvent($id)
    {
        $query = $this->getEntityManager()->createQuery("UPDATE  PlanEventBundle:Event c SET c.nbrplacedispo=c.nbrplacedispo-1 where c.idevent='$id'");
        return $query->getResult();
    }

    public function IncrementNbrPlaceEvent($id)
    {
        $query = $this->getEntityManager()->createQuery("UPDATE  PlanEventBundle:Event c SET c.nbrplacedispo=c.nbrplacedispo+1 where c.idevent='$id'");
        return $query->getResult();
    }
}

