<?php
namespace PlanEventBundle\Repository;
/**
 * ReserveventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyReservations($nomorg){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Reservevent c where c.nomorg='$nomorg' and c.etat='Confirmed'");
        return $query->getResult();
    }

    public function findReservations(){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Reservevent c where c.etat='In Progress'");
        return $query->getResult();
    }

    public function findRejectedReservations($nomorg){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Reservevent c where c.etat='Rejected' and c.nomorg='$nomorg'");
        return $query->getResult();
    }

    public function findProgressReservations($nomorg){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Reservevent c where c.etat='In Progress' and c.nomorg='$nomorg'");
        return $query->getResult();
    }



}