<?php
namespace PlanEventBundle\Repository;
/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindSalle(){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM PlanEventBundle:Salle c");
        return $query->getResult();
    }


}