<?php

namespace ActualityBundle\Repository;

/**
 * ActualitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualitesRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindAll($state){
        $query=$this->getEntityManager()->createQuery("select s from ActualityBundle:Actualites s where s.state='$state'");
        return($query->getResult()) ;
    }



}
