<?php

namespace ActualityBundle\Repository;

/**
 * AsignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignRepository extends \Doctrine\ORM\EntityRepository
{

}
