<?php

namespace MainBundle\Bundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{

}