<?php

namespace MuseumBundle\Repository;

use MuseumBundle\Entity\Demandevisite;
use UserBundle\Entity\User;

/**
 * DemandevisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandevisiteRepository extends \Doctrine\ORM\EntityRepository
{
    //Chercher mes demandes de visite (Client) :  (*:Utilisateur connecté)
    public function findMyRequests($person)
    {
        $query = $this->getEntityManager()->createQuery(" SELECT dv FROM MuseumBundle:Demandevisite dv WHERE dv.source='$person'");
        return $query->getResult();
    }
    //Chercher les visites en cours de traitement (Admin):
    public function findInProgressVisit()
    {
        $query = $this->getEntityManager()->createQuery(" SELECT dv FROM MuseumBundle:Demandevisite dv WHERE dv.etatdv='In progress' ");
        return $query->getResult();
    }

    //Chercher les visites confirmées (Admin):
    public function findConfirmedVisit(){
        $query = $this->getEntityManager()->createQuery(" SELECT dv FROM MuseumBundle:Demandevisite dv WHERE dv.etatdv='Confirmed' ");
        return $query->getResult();
    }




}